/*
 * Copyright 2019 TransferWise Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.transferwise.dynamicform.generator

/**
 * The [StaticFormGenerator] allows to prepend static elements before the elements
 * generated by the [DynamicFormGenerator]. All statically generated items are an
 * integral part of the generated form and contribute to the [DynamicFormState].
 *
 * E.g. This allows to add a name [UserInput.Text] on top of the recipient creation screen.
 */
interface StaticFormGenerator {
    fun generate(
        userInput: Map<UniqueKey, String>,
        serverErrors: Map<UniqueKey, String>,
        showRequired: Boolean
    ): List<UserInput>
}
